server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由功能，利用微服务进行路由（假如下面uri使用的是注释掉的，那么这个可不开启，因为只有一台机器）
      routes:
        - id: payment_routh  #路由的id，没有固定的规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言，路径相匹配的进行路由

        - id: payment_routh2  #路由的id，没有固定的规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求上加一对请求头，名称为X-Request-Id值为1024（一般不在这里配置，而是去自定义过滤器）
          predicates:
            - Path=/payment/lb/**   #断言，路径相匹配的进行路由
            - After=2020-06-06T18:22:56.545+08:00[Asia/Shanghai]  #表示 /payment/lb/** 路径的请求需要在这个时间之后才能正常访问，否则报错
            - Before=2020-09-06T18:22:56.545+08:00[Asia/Shanghai]
            - Between=2020-06-06T18:22:56.545+08:00[Asia/Shanghai],2020-09-06T18:22:56.545+08:00[Asia/Shanghai]
            - Cookie=username,wzm     #表示访问 /payment/lb/** 路径需要带上cookie，名称为username，值为wzm，否则报错（可以使用命令行窗口执行 curl http://localhost:9527/payment/lb --cookie "username=wzm"   不带 --cookie "username=wzm" 则报错）
            - Header=X-Request-Id,\d+  #表示请求头需要有 X-Request-Id 属性，并且值为整数的正则表达式（可以通过 curl http://localhost:9527/payment/lb --cookie "username=wzm" -H "X-Request-Id:123" 测试）
            - Host=**.wzm.org,**.anotherhost.org  #接收一组匹配的域名列表，这个模板是一个ant分割的模板，用.号作为分隔符。它通过参数中的主机地址作为匹配规则（可通过 curl http://localhost:9527/payment/lb --cookie "username=wzm" -H "X-Request-Id:123" -H "Host:www.wzm.org" 测试）
            - Method=GET #表示 GET 请求才允许访问
            - Query=username,\d+   #表示需要带参数，名称为username，值还需要是正整数才允许访问（可通过 curl http://localhost:9527/payment/lb?username=123 --cookie "username=wzm" -H "X-Request-Id:123" -H "Host:www.wzm.org" 测试）

# 整合eureka
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true #表示是否将自己注册进EurekaServer，默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
  # 提供者实例信息配置，完善actuator监控信息
  instance:
    instance-id: cloud-gateway-service
    prefer-ip-address: true     #注册的服务实例访问路径可以显示IP地址

# 整合actuator监控信息
info:
  app.name: wzm-cloud
  company.name: www.wzm.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}