#8004表示注册到Zookeeper服务器的支付服务提供者端口号
server:
  port: 8004


#服务别名，注册到Zookeeper注册中心的名称
spring:
  application:
    name: cloud-paymentzk-service
  cloud:
    zookeeper:
      connect-string: 192.168.1.104:2181
