server:
  port: 8001


spring:
  application:
    name: cloud-provider-hystrix-payment


# 整合eureka
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true #表示是否将自己注册进EurekaServer，默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合Ribbon使用负载均衡
  # 提供者实例信息配置，完善actuator监控信息
  instance:
    instance-id: cloud-provider-hystrix-payment8001
    prefer-ip-address: true     #注册的服务实例访问路径可以显示IP地址


# 整合actuator监控信息
info:
  app.name: wzm-cloud
  company.name: www.wzm.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}